#!/bin/bash

# Fail hard when anything fails
set -e
set -o pipefail

# use regexp in filename globbing
shopt -s extglob  

TARGET_FILE=$(date +%Y%m%d-%H%M%S)_dump.tar.gz

umask 0066

echo Dumping ...
cd /var/lib/powerdns
for file in pdns.lmdb pdns.lmdb-+([0-9]); do echo $file; mdb_dump -f /tmp/$file.dump -n -a $file; done

echo Zipping ...
cd /tmp
tar czf /backup/${TARGET_FILE} *.dump

echo Done.
du -h /backup/${TARGET_FILE}
