global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'desec-ns'

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'openvpn-client'
    static_configs:
      - targets: ['openvpn-client_monitor:9176']
  - job_name: 'dnsdist'
    static_configs:
      - targets: ['dnsdist:8083']
    basic_auth:
      username: arbitrary
      password: we+ensure+security+via+network+segmentation
  - job_name: 'knot-exporter'
    static_configs:
      - targets: ['knot-exporter:9433']
